"""ResearchState — the single source of truth passed between graph nodes."""

from __future__ import annotations

from typing_extensions import TypedDict


class ResearchState(TypedDict):
    """Mutable state bag threaded through every node in the research graph.

    Attributes:
        goal: The original research question supplied by the user.
        plan: Sub-queries generated by the planner node.
        urls_found: All candidate URLs collected by the searcher node.
        urls_scraped: URLs that were successfully scraped and ingested.
        findings: Short human-readable summaries, one per ingested URL.
        report: The final synthesised report written by the synthesiser node.
        iteration: Loop counter incremented by the planner; guards against
            infinite loops (capped at ``settings.agent_max_iterations``).
        status: Current lifecycle phase.  One of:
            ``"planning"``  | ``"searching"``  | ``"scraping"``
            ``"synthesising"`` | ``"evaluating"`` | ``"done"``
    """

    goal: str
    plan: list[str]
    urls_found: list[str]
    urls_scraped: list[str]
    findings: list[str]
    report: str
    iteration: int
    status: str
